Push snaphots to Dockerhub for commits tagged `latest-snapshot-*`
Teradata/docker-images pull request #6
Opened 2016-10-24 15:28 UTC by ArturGajowy

This already worked in production here:
https://travis-ci.org/Teradata/docker-images/builds/169562896

2016-10-26 06:25 UTC, kokosing requested changes

2016-10-26 06:25 UTC, kokosing commented on .travis.yml
> +  - git branch -D master || true
really? lol

Maybe I could extend `docker-release` to support publishing from different branches?

2016-10-27 13:33 UTC, ArturGajowy commented on .travis.yml
> +  - git branch -D master || true
Let me know when https://github.com/kokosing/docker-release/pull/9 is done then :)

2016-10-28 06:06 UTC, kokosing commented on .travis.yml
> +  - git branch -D master || true
done

2016-10-28 14:09 UTC, closed without merging