Changes required to test _HOST placeholder in kerberos principal
Teradata/docker-images pull request #9
Opened 2016-12-28 22:00 UTC by arhimondr

- Allow `presto-server` user to impersonate. Further `presto-server/_HOST` principal will be used as a proxy user on `presto-master`
- Create `hive/presto-master` principal.  Further `hive/_HOST` principal will be used as a proxy user on `presto-master`

2016-12-28 22:46 UTC, amrutagokhale requested changes

2016-12-28 22:46 UTC, amrutagokhale commented on teradatalabs/cdh5-hive/files/setup.sh
> +rm -rf /etc/security/limits.d/hdfs.conf
No need to add the command in this file. Line #8 is doing the same.

2016-12-28 22:46 UTC, amrutagokhale commented on teradatalabs/cdh5-hive-master/files/setup.sh
> +rm -rf /etc/security/limits.d/hdfs.conf
Is `-rf` needed here? Ditto for the command in other `setup.sh` files too.

2016-12-28 22:46 UTC, amrutagokhale commented on teradatalabs/cdh5-hive-kerberized/Dockerfile
> +RUN /usr/sbin/kadmin.local -q "xst -norandkey -k /etc/presto/conf/presto-hive.keytab hive/presto-master"
The filename `presto-hive.keytab` is a little confusing. Is this name auto-generated or did you specify it? If it is the latter, does it make sense to rename this to say `hive-presto-master.keytab` or something that makes it more clear?

2016-12-29 16:56 UTC, cawallin approved these changes

2016-12-29 17:03 UTC, amrutagokhale approved these changes

2016-12-29 18:44 UTC, merged